# Версия формата файла Docker Compose
version: '3'

# Определение сервисов/контейнеров
services:
  # Сервис сервера Pyroscope (система для анализа производительности)
  pyroscope-server:
    # Используем официальный образ Pyroscope от Grafana с конкретной версией
    image: grafana/pyroscope:1.13.2
    # Пробрасываем порты: порт 4040 контейнера на порт 4040 хоста
    ports:
      - "4040:4040"

  # Сервис Node.js приложения
  node-app:
    # Собираем образ из Dockerfile в текущей директории
    build: .
    # Пробрасываем порты: порт 3000 контейнера на порт 3000 хоста
    ports:
      - "3000:3000"
    # Переменные окружения для конфигурации приложения
    environment:
      # Адрес сервера Pyroscope для отправки данных профилирования
      PYROSCOPE_SERVER_ADDRESS: "http://pyroscope-server:4040"
    # Зависимости: этот сервис зависит от pyroscope-server
    # и будет запущен только после его успешного старта
    depends_on:
      - pyroscope-server
