env:
  GF_INSTALL_PLUGINS: grafana-pyroscope-app
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.apatsev.org.ru
  paths:
    - /

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Grafana Pyroscope
        type: grafana-pyroscope-datasource
        url: http://pyroscope.pyroscope:4040
        jsonData:
          minStep: '15s'
