env:
  GF_INSTALL_PLUGINS: grafana-pyroscope-app
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.apatsev.org.ru
  paths:
    - /

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Pyroscope
        type: pyroscope
        access: proxy
        url: http://pyroscope.pyroscope.svc.cluster.local:4040
        isDefault: false
        version: 1
        editable: true
